obj = xpixels.o
bin = xpixels

include cfg.mk

CFLAGS = -O3 $(CFLAGS_cfg) $(CFLAGS_user)
LDFLAGS = $(LDFLAGS_cfg) $(LDFLAGS_user) -lX11 -lXext -lm

$(bin): $(obj)
	$(CC) -o $@ $(obj) $(LDFLAGS)

.PHONY: clean
clean:
	rm -f $(obj) $(bin)
