obj = sdl2pixels.o
bin = sdl2pixels

include cfg.mk

CFLAGS = -O3 `sdl2-config --cflags` $(CFLAGS_cfg) $(CFLAGS_user)
LDFLAGS = $(LDFLAGS_cfg) $(LDFLAGS_user) `sdl2-config --libs` -lm

$(bin): $(obj)
	$(CC) -o $@ $(obj) $(LDFLAGS)

.PHONY: clean
clean:
	rm -f $(obj) $(bin)
