obj = glpixels.o
bin = glpixels

include cfg.mk

CFLAGS = -O3 $(CFLAGS_cfg) $(CFLAGS_user)
LDFLAGS = $(LDFLAGS_cfg) $(LDFLAGS_user) -lglut -lGLU -lGL -lX11 -lXext -lXmu -lm

$(bin): $(obj)
	$(CC) -o $@ $(obj) $(LDFLAGS)

.PHONY: clean
clean:
	rm -f $(obj) $(bin)
