obj = sdlpixels.o
bin = sdlpixels

include cfg.mk

CFLAGS = -O3 `sdl-config --cflags` $(CFLAGS_cfg) $(CFLAGS_user)
LDFLAGS = $(LDFLAGS_cfg) $(LDFLAGS_user) `sdl-config --libs` -lm

$(bin): $(obj)
	$(CC) -o $@ $(obj) $(LDFLAGS)

.PHONY: clean
clean:
	rm -f $(obj) $(bin)
